### ISSUE TITLE
Custom moon won't load

### ISSUE THREAD

**Issue by Teapottt** [IAmBatby/LethalLevelLoader#103]
Everytime I try to go to the menu it just gets stuck on this warning and nothing else happens
![Screenshot 2024-05-16 190217](https://github.com/IAmBatby/LethalLevelLoader/assets/149398659/6e0ac090-9d57-452a-8f21-f003b93507bd)

**Comment by Sveiv** [comment]
Still doesnt work for me

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
