### ISSUE TITLE
[Issue] new issues in 1.2.3

### ISSUE THREAD

**Issue by CoolLKKPS** [IAmBatby/LethalLevelLoader#105]
@IAmBatby 
1. ship won't leave in the company even u pull the lever (#100)
2. most the time, if u only install custom moon mods, u cannot able to enter the game main menu and stuck at launch mode interface (#102)

**Comment by TesterHere06** [comment]
Yuuup... Stuck on company building

**Comment by Vomitblood** [comment]
duplicate of #100, take a look at LethalLevelLoaderCompanyFixer mod to fix v1.2.3
or downgrade to v1.2.2

**Comment by CoolLKKPS** [comment]
> duplicate of #100, take a look at LethalLevelLoaderCompanyFixer mod to fix v1.2.3 or downgrade to v1.2.2

will edit in the first post, ahh i hate it... and i'd report a false issue

**Comment by CoolLKKPS** [comment]
will re-open it if i found new issues about 1.2.3
