### ISSUE TITLE
How do the Dungeon Injection Settings work? – Proposing more priority on documentation

### ISSUE THREAD

**Issue by DreamyK9** [IAmBatby/LethalLevelLoader#110]
I am super confused about the "Dungeon Injection Settings".

If there are no Mods, Levels or Tags set for an Interior/Dungeon, how is its generation weight on moons determined? Are there default values?  

Does LethaLevelLoader take priority over individual configs, when "Enable Content Configuration" is set to true?
Do I even interpret it right, that this option makes changes to the config effective?
 
 There's a lot of questions and I can't seem to find any place on the internet where they are answered.
I think there should at least be a small note on the behaviour of most settings in the config file. This would make it a ton easier for modpack creators to tweak them.
I'd be glad to help with that as best as I can.

**Comment by IAmBatby** [comment]
Completely valid proposal but due to IRL circumstances working on LethalLevelLoader is barely viable in itself let alone creating and maintaining documentation. I completely understand the interest and would love to be able to resolve this in the future.
