### ISSUE TITLE
See Moon Pricing on Terminal

### ISSUE THREAD

**Issue by Mr-Twave** [IAmBatby/LethalLevelLoader#12]
I'd love to see in parenthesis next to each moon a (•x) for the amount of credits rather than having to go through each moon to figure out what the cost is. Could you have a toggle for this? [the reason why I ask you of this here instead of a terminal API mod is because it needs compatibility with extra moons.]

Also as a gift, here's a minimalist modpack with all the best moons and a leveling system with many useful QoL features. I went through every single moon modpack there was, and I wanted to make the modpack as vanilla as possible otherwise. Cheers! (80 mods, half of which are QoL. A few you don't need to install.)
Works in the Thunderstore: 018d5918-095a-d08d-9949-9e38004adae4

**Comment by darkanx** [comment]
Very much need this feature. Would also be nice to have planets sorted by price or rating.

**Comment by Mr-Twave** [comment]
sort by;
default
risk level
price

so a toggle for;
-risk level
-price

your suggestion seems pretty good.

**Comment by Mr-Twave** [comment]
I'll help with coding this in fact. Here's some suggested code;

`using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

public class TerminalSettings : MonoBehaviour
{
    [SerializeField]
    private List<Item> items = new List<Item>();

    public enum SortType
    {
        Default,
        RiskLevel,
        Price
    }

    public enum DisplayOptions
    {
        RiskLevel,
        Price
    }

    [SerializeField]
    private SortType currentSort = SortType.Default;
    
    [SerializeField]
    private List<DisplayOptions> displayOptions = new List<DisplayOptions>();

    private void Start()
    {
        // Example sorting and displaying based on set options.
        SortItems();
        DisplayItems();
    }

    public void SetSortType(SortType sortType)
    {
        currentSort = sortType;
        SortItems();
        DisplayItems();
    }

    public void SetDisplayOptions(List<DisplayOptions> options)
    {
        displayOptions = options;
        DisplayItems();
    }

    private void SortItems()
    {
        switch (currentSort)
        {
            case SortType.Default:
                items = items.OrderBy(i => i.Name).ToList();
                break;
            case SortType.RiskLevel:
                items = items.OrderBy(i => i.RiskLevel).ToList();
                break;
            case SortType.Price:
                items = items.OrderBy(i => i.Price).ToList();
                break;
        }
    }

    private void DisplayItems()
    {
        foreach (var item in items)
        {
            string displayString = item.Name;
            
            if (displayOptions.Contains(DisplayOptions.RiskLevel))
            {
                displayString += $" (Risk: {item.RiskLevel})";
            }
            
            if (displayOptions.Contains(DisplayOptions.Price))
            {
                displayString += $" (Price: {item.Price})";
            }

            Debug.Log(displayString);
        }
    }
}

[Serializable]
public class Item
{
    public string Name;
    public int RiskLevel;
    public float Price;

    public Item(string name, int riskLevel, float price)
    {
        Name = name;
        RiskLevel = riskLevel;
        Price = price;
    }
}`

`// Adding Enums for Sorting and Display Preferences
public enum SortType {
    Default,
    RiskLevel,
    Price
}

public enum DisplayPreference {
    RiskLevel,
    Price
}

public class TerminalCommandHandler : MonoBehaviour {
    // Existing code for handling terminal commands and display omitted for brevity

    private SortType currentSort = SortType.Default;
    private List<DisplayPreference> currentDisplayPreferences = new List<DisplayPreference>();

    // Method to update sorting type based on terminal command
    public void UpdateSortType(string sortCommand) {
        // Parse sortCommand to update currentSort appropriately
        // Example:
        if (sortCommand.Equals("sort-risk", StringComparison.OrdinalIgnoreCase)) {
            currentSort = SortType.RiskLevel;
        } else if (sortCommand.Equals("sort-price", StringComparison.OrdinalIgnoreCase)) {
            currentSort = SortType.Price;
        } else {
            currentSort = SortType.Default;
        }

        // Ideally, re-fetch and sort the data (e.g., moons) based on currentSort
        SortAndDisplayMoons(); // Placeholder method
    }

    // Method to update display preferences based on terminal command
    public void UpdateDisplayPreferences(List<DisplayPreference> preferences) {
        currentDisplayPreferences = preferences;
        // Re-display moons based on updated preferences
        SortAndDisplayMoons(); // Placeholder method
    }

    private void SortAndDisplayMoons() {
        // Placeholder for fetching, sorting, and displaying moons based on currentSort and currentDisplayPreferences

        // Sorting logic based on currentSort (Default, RiskLevel, Price)
        // Display logic that checks currentDisplayPreferences to decide whether to include risk level, price, etc., in the output.

        // Example output method call:
        // DisplayMoons(sortedMoons, currentDisplayPreferences);
    }

    // Additional methods to handle terminal commands, fetch data, sort, and display output would be implemented as needed
}
`

`// Assuming Moon.cs and TerminalCommandHandler.cs are part of our namespace
using System.Linq;
using System.Collections.Generic;

public class Moon {
    public string Name;
    public string RiskLevel; // Considering Risk Levels as String for simplicity, e.g., "F", "D", "C", "B", "A", "S-", "S", "S+", "SS", "P", "Unknown"
    public decimal Price;

    public Moon(string name, string riskLevel, decimal price) {
        Name = name;
        RiskLevel = riskLevel;
        Price = price;
    }
}

public class TerminalCommandHandler : MonoBehaviour {
    private SortType currentSort = SortType.Default;
    private List<DisplayPreference> currentDisplayPreferences = new List<DisplayPreference>();
    // Placeholder for a method that fetches moons (assuming it returns a List<Moon>)
    private List<Moon> GetAllMoons() => new List<Moon>();

    private void SortAndDisplayMoons() {
        List<Moon> moons = GetAllMoons();

        // Sort
        switch (currentSort) {
            case SortType.RiskLevel:
                moons = moons.OrderBy(m => m.RiskLevel).ToList(); // Note: Custom sort logic might be needed for non-numeric risk levels
                break;
            case SortType.Price:
                moons = moons.OrderBy(m => m.Price).ToList();
                break;
        }

        // Display
        foreach (var moon in moons) {
            List<string> displayInfo = new List<string> { moon.Name };
            if (currentDisplayPreferences.Contains(DisplayPreference.RiskLevel)) {
                displayInfo.Add($"Risk: {moon.RiskLevel}");
            }
            if (currentDisplayPreferences.Contains(DisplayPreference.Price)) {
                displayInfo.Add($"Price: {moon.Price.ToString("C")}");
            }

            string displayString = string.Join(" ", displayInfo);
            Debug.Log(displayString); // Or send the displayString to the terminal's output mechanism
        }
    }

    // Methods to UpdateSortType, UpdateDisplayPreferences, etc., as previously outlined.`

**Comment by Mr-Twave** [comment]
Hey @IAmBatby , is there anything I can do to help you with more specific implementation of this code? It looks like some of your more recent commits are more relevant to the game than the superficial code I'd provided.

**Comment by IAmBatby** [comment]
Unfortunately this feature was implemented before this issue and concepted code was created. Will be in the forthcoming release of LethalLevelLoader.

**Comment by Mr-Twave** [comment]
Can I be of any help?

**Comment by IAmBatby** [comment]
The overhaul to the Terminal is already fully complete, Thank you.

**Comment by Mr-Twave** [comment]
Hey. I thought you might not be fully aware, so I wanted to make this list explicitly for you. One of the levels made with your code have their difficulty set at "B+". Will your code be able to handle this case?
"F [I haven't seen a mod with]", "D-[ihsamw]", "D", "D+[ihsamw]", "C-[ihsamw]", "C", "C+[ihsamw]", "B-[ihsamw]", "B", "B+", "A-[ihsamw]", "A", "A+", "S-[ihsamw]", "S", "S+", "SS", "P", "Unknown"
