### ISSUE TITLE
Custom enemies made with Lethal Lib cannot spawn on custom moons

### ISSUE THREAD

**Issue by Entity378** [IAmBatby/LethalLevelLoader#13]
Custom enemies created with Lethal Lib cannot spawn on custom moons loaded with LethalLevelLoader. I have attempted multiple times, but the entries for the custom enemies are not present in the list of enemies that can spawn. However, on any other moon, including custom ones added with LethalExpansionCore, the custom enemys spawns correctly.

**Comment by josuaman** [comment]
same

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
