### ISSUE TITLE
The company cruiser dropship dont works in custom moons V60

### ISSUE THREAD

**Issue by Dreamer-Prime** [IAmBatby/LethalLevelLoader#139]
Hi, I'm new to creating custom maps, I recently created a custom map for V55 with LLL and NomNomLCPatcher
but when I update the map for the new version V61 it has some problems with the delivery ship, when I order the company cruiser instead of arriving next to the delivery ship, the vehicle spawns instantly in a fixed place on the map, usually going through the ground near the home ship

The first image is my custom map and the second one is a test map and in both the same problem happens.

<img width="1280" alt="errr f2" src="https://github.com/user-attachments/assets/987d586e-7a30-4fb6-bebe-62bbb9cb5f37">

<img width="1280" alt="errr f" src="https://github.com/user-attachments/assets/3b18689a-4d56-4959-9245-c1b33e765845">

**Comment by DHStyle541** [comment]
you have this is?
https://thunderstore.io/c/lethal-company/p/DiFFoZ/CompanyCruiserFix/

because modded moons rn need that

**Comment by Dreamer-Prime** [comment]
> you have this is? https://thunderstore.io/c/lethal-company/p/DiFFoZ/CompanyCruiserFix/
> 
> because modded moons rn need that




the same thing happens :c


![image](https://github.com/user-attachments/assets/b88580ae-2914-4357-9968-3d2ed989a224)


![test](https://github.com/user-attachments/assets/d71a0cad-fef1-41b6-8f1f-1e70ede33a3b)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <066a7b7eb8c24d4facd1e255e669803f>:IL_02B4)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <066a7b7eb8c24d4facd1e255e669803f>:IL_018B)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <066a7b7eb8c24d4facd1e255e669803f>:IL_02B4)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <066a7b7eb8c24d4facd1e255e669803f>:IL_018B)



I guess I'll wait to see if this issue is resolved with LLL version 1.3.11.

**Comment by Dreamer-Prime** [comment]
I found out what was causing the cruiser company crash, and it had nothing to do with the lethal level loader, the Imperium mod was the one causing that problem
