### ISSUE TITLE
Incompatible w korean patch

### ISSUE THREAD

**Issue by Piggy3590** [IAmBatby/LethalLevelLoader#14]
landing on the modded moon with the unofficial korean patch installed causes an error.
korean patch may have little issues because it was developed before Lethal Company's BepInEx was released. Typically, when an asset is replaced, the internal name of the item changes.
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14151034/LogOutput.log)
^ SecretLabs, (Error occurs from line 1003)
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14151053/LogOutput.log)
^ E Gypt, (Error occurs from line 292)

Downgrading LethaLib doesn't work.

**Comment by 10sa** [comment]
I have same problem like this issue. I try landing with korean patch and only LethalLevelLoader and SecretLabs mods, but next error are threw and just can't land.

@Piggy3590 If you fine, can you post korean patch files here? might be that helpful for developer.

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoundManager.SpawnScrapInLevel () (at <af9b1eec498a45aebd42601d6ab85015>:IL_03D7)
RoundManager.GeneratedFloorPostProcessing () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0009)
RoundManager+<LoadNewLevelWait>d__115.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)
```

**Comment by IAmBatby** [comment]
Resolved in future versions of the project. If more translation related issues show up in the future feel free to open another Issue.
