### ISSUE TITLE
[BUG] LLL is just too confused 

### ISSUE THREAD

**Issue by MarcBrown1009** [IAmBatby/LethalLevelLoader#150]
Another bug same as usual, still freakingly-freezing screen when starting the game. I used to uninstall the file LethalDataModLib by MaxWasUnavailable but it, was like "fine" on the OutputLog console with no errors so I thought the problem would be the LethalLevelloader. The version I recently play is v64, it's going to be updated to v65 for the 1st aniversary of the game so ... I just want to play modded maps/interiors. Anyone knows the error I've been struggling with ?
Here is the screenshot bug and outputlog.txt: 
screen shot:
![794f8a58-d13c-46e4-b4de-e3019e2f8250](https://github.com/user-attachments/assets/aa5f0089-2a0e-4565-bcbe-7636b3b1fdd5)
output log:
[LogOutput.log](https://github.com/user-attachments/files/17653253/LogOutput.log)

**Comment by IAmBatby** [comment]
Not LethalLevelLoader's doing. Report this bug to the author of Multiple Weather Effects.

**Comment by MarcBrown1009** [comment]
Thank you so much~, I don’t even know that sided mod would take me so long
to fix

Vào Th 5, 7 thg 11, 2024 lúc 08:04 IAmBatby ***@***.***> đã
viết:
