### ISSUE TITLE
The list of custom moons disappears

### ISSUE THREAD

**Issue by BAHEK-BOP** [IAmBatby/LethalLevelLoader#16]
The list of custom moons disappears after installing the mod, which translates the entire game and mods into Russian 
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/017b46cf-4cb8-406b-9e80-1d103f093e4e)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/16e61fda-a178-4750-8488-9a5221585f24)
I also threw off the list of mods

If I remove these mods, then everything falls into place
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/b0230f86-4376-4bb6-9c6a-6999b4c50f9b)

I contacted the developer of this mod first, but he told me that it was the fault of this LLL mod, saying: 
"The LLL developer has not yet updated the core for moons and generation, so the problem has not been solved. Lethal Expansion dominates, and its method of showing moons in the terminal above is not the same as that of LLL. So there is no list of moons"

**Comment by AndreyMrovol** [comment]
> The list of custom moons disappears after installing the mod, which translates the entire game and mods into Russian ![image](https://private-user-images.githubusercontent.com/157053836/302721000-017b46cf-4cb8-406b-9e80-1d103f093e4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTM1NzksIm5iZiI6MTcwNzI5MzI3OSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNzIxMDAwLTAxN2I0NmNmLTRjYjgtNDA2Yi05ZTgwLTFkMTAzZjA5M2U0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwODA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWU3NjRmM2IzYjk1ZjljMjJjNjhlYWNhNmI5OGEzYmJmZDQxNDE2OGQ3MTY2ZmNhMWM2MTQ3NzI0NjE1NmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d89uEnPgpEzyGynPVlI_QHJ0LwJesKtFGWZUThm-NSQ) ![image](https://private-user-images.githubusercontent.com/157053836/302721023-16e61fda-a178-4750-8488-9a5221585f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTM1NzksIm5iZiI6MTcwNzI5MzI3OSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNzIxMDIzLTE2ZTYxZmRhLWExNzgtNDc1MC04NDg4LTlhNTIyMTU4NWYyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwODA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDZmZTUyOTczMzZjZDc5NzVkYWMxNmU2OTc2MWJhOTQ2NWRmN2Y3YjAwM2YwOTc3NzZkMGUzYTk3MzcxNWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dWzViiNRecSYwoH4IPo22Foas6mQmFgdRFhHUWckJX0) I also threw off the list of mods
> 
> If I remove these mods, then everything falls into place ![image](https://private-user-images.githubusercontent.com/157053836/302721184-b0230f86-4376-4bb6-9c6a-6999b4c50f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTM1NzksIm5iZiI6MTcwNzI5MzI3OSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNzIxMTg0LWIwMjMwZjg2LTQzNzYtNGJiNi05YzZhLTY5OTliNGM1MGY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwODA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODcxY2MyNDhhODlkYWIzZmE1MDYxMmE4ZDQwMTQwOWUwMjU5N2I4NzgxNTc1MDhjNzY3MTA5ZmRmZWY2NzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LrJVuBln1FLYQmhmFlUJBtrwTenUqvCofE3-8jUvtTU)
> 
> I contacted the developer of this mod first, but he told me that it was the fault of this LLL mod, saying: "The LLL developer has not yet updated the core for moons and generation, so the problem has not been solved. Lethal Expansion dominates, and its method of showing moons in the terminal above is not the same as that of LLL. So there is no list of moons"

This is the same issue that was reported to me (https://github.com/AndreyMrovol/LethalWeatherTweaks/issues/5#issuecomment-1930074104) - translation mod patches `LoadNewNode` as a prefix, which prevents LLL's list to display.
