### ISSUE TITLE
THE TERMINAL IS NOT WORKING

### ISSUE THREAD

**Issue by BAHEK-BOP** [IAmBatby/LethalLevelLoader#17]
I created a new world, connected, and then this! SOMEONE TURN ON THE TERMINAL FOR ME!
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/27342037-8fbc-4957-b689-bdc5b33907e5)

MODPACK CODE 018d8613-3782-c4d7-2abd-e963d3b4fca5

I'll turn on the console and show you what's there

**Comment by BAHEK-BOP** [comment]
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14202966/LogOutput.log)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/aa04e590-821d-41ce-b70a-7633ab1e8fbc)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/a48d8acc-01e3-4325-b6dc-cd2d5af34f33)

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/325b96db-dcf3-4329-9dfa-24db53476ad8)
mb here is the error

**Comment by bchewy15** [comment]
Yep, same issues here. New update an hour ago had some changes related to terminal.

**Comment by TonyZeit** [comment]
Same.

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/2ef8ad00-468c-456f-bc31-63099668fe6a)
I off HookGenPatcher To find out which mod is preventing it from loading. and my terminal learned to work! Yippee
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/46b0249e-6bd9-46f4-ba86-ce7c809b9197)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/2564adb8-b20d-4d9d-92ba-8ebcd9255bc9)

**Comment by trivenge** [comment]
Same issue has occurred

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/5b6ecf4a-7922-4143-a4dc-0e8d57d8795d)
LLL and Lethal Expansion do not work together again
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14203272/LogOutput.log)

I turned off the moons Lethal Expansion to test and find problems faster

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/f5731089-c3a2-41bc-a9df-420db78d4ac1)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/03a68b5a-19a1-4d80-971e-61a6197e2535)
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14203306/LogOutput.log)

Doesn't launch to the moon

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/18d76c3d-e966-42ba-af42-059140cd1771)
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/4951a5b7-9542-4950-be8a-f6a8df5584f1)

it turns out that the mod itself does not work

**Comment by BAHEK-BOP** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/8d534c55-3a89-4b44-86fe-3f85e321bef2)
I thought maybe I was doing something wrong, tried another planet and completely removed the fashion. But the result is the same
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/157053836/a61b803c-7d1c-4a0f-a115-3e7bccddd033)

**Comment by Mr-Twave** [comment]
[Info   :Lethal Progression] 0 players, 0 quotas, 38 initial cost, 0 person value, 0 quota value, 38 total cost.
[Info   : Unity Log] [SS]: Successfully loaded saved suit. (GlowStick06Blue)
[Info   : Unity Log] [HELMET_CAMERAS] Ship camera founded...
[Info   : Unity Log] [HELMET_CAMERAS] Monitors were changed...
[Info   : Unity Log] [HELMET_CAMERAS] Turning off vanilla internal ship camera
[Info   : Unity Log] Set interminalmenu to true: True
[Info   : Unity Log] Caught error while entering computer terminal. Exiting player from terminal. Error: System.NullReferenceException: Object reference not set to an instance of an object
  at LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) [0x00001] in <eca1ebebd4b94f3cab7421984412c229>:IL_0001
  at (wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
  at (wrapper dynamic-method) Terminal.DMD<Terminal::BeginUsingTerminal>(Terminal)
[Info   : Unity Log] Quit terminal; inTerminalMenu true?: {playerScript.inTerminalMenu}
[Info   : Unity Log] PLAYER OPENED MENU
[Info   : Unity Log] In terminal menu: False

**Comment by Lerrycapetime** [comment]
1.1.1 just released but R2 is a bit sluggish at letting anyone download it

**Comment by Qugar** [comment]
The terminal now works a little better, but you can no longer land the ship.

**Comment by ManGuyNY** [comment]
v1.1.1 fixed the terminal not working at all for me, but now the "MOONS" cmd doesn't show all of my modded moons. I can still route to them, they just don't print out on the list.

**Comment by Qugar** [comment]
Unfortunately there is no improvement with v1.1.2 either. Not all moons always appear in the list. I can route to the moon but can't land.

**Comment by BAHEK-BOP** [comment]
With the version of Lethal Expansion 1.3.35 and LLL 1.1.3, EVERYTHING WORKS FINE
