### ISSUE TITLE
1.1.1 Modded moons not in moon list

### ISSUE THREAD

**Issue by darkanx** [IAmBatby/LethalLevelLoader#18]
Just loaded up the newest patch, and its running again, but the moon list does not show modded moons. I thought maybe I needed to set something in the config to list them, but nothing I changed there added them to the list.

Also would very much like for there to be an option to turn off the empty lines between every 3 planets.

Thank you for your excellent work! I am sure you have been frantically stomping bugs since you put out a new major update, but we all appreciate it!

**Comment by Mr-Twave** [comment]
Kudos to the mod owner for their efforts. I can see the frantic coding they're in and they're doing quite a bit to make this mod work. Much appreciated.

**Comment by darkanx** [comment]
Status: Primary issue fixed. 
Cause: moons were all LethalExpansion moms.
New Issue: LE moons are all price 0 (author likely aware of this and will be fixed in the future).

**Comment by IAmBatby** [comment]
Resolved as Lethal Expansion is now deprecated.
