### ISSUE TITLE
[New Issue for 1.1.2] the game won't load the map after the first game

### ISSUE THREAD

**Issue by CoolLKKPS** [IAmBatby/LethalLevelLoader#19]
[Error  : Unity Log] RuntimeNavMeshBuilder: Source mesh Cylinder is skipped because it does not allow read access
[Error  : Unity Log] RuntimeNavMeshBuilder: Source mesh toilet_b is skipped because it does not allow read access
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
LethalLevelLoader.LethalLevelLoaderNetworkManager.__rpc_handler_12573863 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <0ee8da500aa942f89ba9acde1681b0ff>:IL_007B)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
LethalLevelLoader.LethalLevelLoaderNetworkManager:GetRandomExtendedDungeonFlowServerRpc()
LethalLevelLoader.DungeonLoader:SelectDungeon()
LethalLevelLoader.Patches:InjectHostDungeonFlowSelection()
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
RoundManager:DMD<RoundManager::__rpc_handler_1193916134>(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
RoundManager:DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager, Int32, Int32)
<LoadNewLevelWait>d__115:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by M200mywife** [comment]
Try to turn off Lethal Expansion or Lethal Expansion Core

**Comment by IAmBatby** [comment]
Should be resolved in 1.1.0.3.
