### ISSUE TITLE
Breaks Terminal Moon List From Showing Modded Moons

### ISSUE THREAD

**Issue by AutTheWizard** [IAmBatby/LethalLevelLoader#2]
I want to use this mod because new interiors is awesome, however at this moment it causes the moons list to default to the vanilla moons list when searching moons if you have moon mods installed.

**Comment by IAmBatby** [comment]
As mentioned in the description, Because both mods alter the same aspect of the base game, using Lethal Expansion is not supported. In the mean time I suggest looking into LethalExpansionCore as it has made adjustments to allow the use of Lethal Expansion alongside this mod.

**Comment by AbandonedPlayer** [comment]
> As mentioned in the description, Because both mods alter the same aspect of the base game, using Lethal Expansion is not supported. In the mean time I suggest looking into LethalExpansionCore as it has made adjustments to allow the use of Lethal Expansion alongside this mod.

This worked for me. Using LethalExpansionCore and LethalExpansion in conjuction makes the moded moons show back up in the terminal.

**Comment by TeraTyrantShadic** [comment]
Testing it myself with the latest update, it does not work with these moon mods; Orion, Ether, Ducks Moons, Atlas Abyss, SecretLabs, Aquatis & Kast. By that I mean it doesn't show up in the moon list and it only shows egypt even when both Lethal Expansion and Core are activated even with the config setting, UseOriginalLethalExpansion is set to true and LoadDefaultBundles is set either to true or false. Is there a solution? cause I am testing this on a fresh new profile with only the moons, lethal expansion and core and the Lethal level Loader is still hiding the other modded moons.

**Comment by DarkoPendragon** [comment]
> Testing it myself with the latest update, it does not work with these moon mods; Orion, Ether, Ducks Moons, Atlas Abyss, SecretLabs, Aquatis & Kast. [...]

Can confirm, using LethalExpansionCore ontop of LethalExpansion resolved the issue of custom moons not loading. Leave your defaults for the mods alone in the configs and install both LethalExpansion and the Core mod. It didn't work without LethalExpansion installed as well (might be my fault though).
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/28911975/3847e335-6632-49cb-9151-9c6bed085d3c)

**Comment by TeraTyrantShadic** [comment]
So everything has to be set at default to work, checked and it is fixed. Is there a possibility for a future update for it to work with UseOriginalLethalExpansion when set to true? There are some mods that requires the config option to be set to true in order to use them without the screen blacking out with a green haze.

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
