### ISSUE TITLE
Didn't list all modded moons but a few.

### ISSUE THREAD

**Issue by M200mywife** [IAmBatby/LethalLevelLoader#20]
Besides, I installed 4 moons(Orion, Wateridge, Celest, Aquatis) from LethalExpansionCore and LEDefaultModules but they didn't display in the terminal like the former patch ; I played the same profile yesterday and everything worked properly as well.

![ads](https://github.com/IAmBatby/LethalLevelLoader/assets/105147350/82fee1c2-689c-433b-a101-b05e8c26014d)
![adss](https://github.com/IAmBatby/LethalLevelLoader/assets/105147350/9410d9e6-af17-4051-adff-01e0144fd4e6)
![casd](https://github.com/IAmBatby/LethalLevelLoader/assets/105147350/233ac9eb-25f8-4f45-9180-63f06c6179e0)

These moons are loaded and detectable but unable to display in the terminal.

**Comment by M200mywife** [comment]
solved. Thank for ur timely

**Comment by 1753449579** [comment]
怎么解决的，我也这样
