### ISSUE TITLE
Can't land on modded moons

### ISSUE THREAD

**Issue by Qugar** [IAmBatby/LethalLevelLoader#22]
Since version 1.1.0 I can no longer land on a modded moon. I pull the lever and then nothing happens. The only error message I get from BepInEx is the following:

![grafik](https://github.com/IAmBatby/LethalLevelLoader/assets/8191849/b7b5aa6c-c08c-4c88-8785-75c44324fcf5)

Mod-Profile:018d8889-0a3c-1172-3e7f-11916e705ad4

With version 1.0.7 everything worked perfectly.

**Comment by BoniatoRelleno** [comment]
Its an incompatibility with Intro Tweaks, try without it

**Comment by Qugar** [comment]
Looks like every mod that auto-selects online is now incompatible, would it be possible to add this option to LethaLevelLoader in the future? That was the main reason why I had IntroTweaks.

**Comment by DHStyle541** [comment]
all mods with AutoSelect = Online/Lan incompatible because LLL

**Comment by Owen3H** [comment]
My insight as the author of IT.
While I could just default `sAutoSelectMode` to OFF or patch slightly later, it isn't really a *solution*.

LLL, LE and future loader mods should avoid patching `PreSceneInitScript` so mine and other "skip" mods stay compatible.
I suggest loading bundles on the game loading screen and maybe display something like "Loading Bundles (2/10)".

**Comment by IAmBatby** [comment]
PreSceneInitScript was targeted as it's a good entry point after the game window has initialized and before GameNetworkManager starts on the next scene. I can look into going even earlier when I work more next week but I don't think other mods completely avoiding touching that aspect of the game is viable in the longterm.

**Comment by Owen3H** [comment]
By 'avoid', I am specifically referring to loading asset bundles or other logic that could take a long time.
I do agree that skipping a scene is not ideal, but in this case it doesn't do anything important.

Doing bundle loading in `Awake` instead should keep the game from opening until they are all done which I think is the easiest solution here if it cannot be done after `GameNetworkManager`. 

In the meantime I will look into making the launch options skipping more future-proof.

**Comment by Jocosityy** [comment]
For what it's worth, I use LC FastStartup (which also skips the Online/LAN choice) and I haven't had this problem with the newer LLL versions. Maybe it does it using a different method?

**Comment by Qugar** [comment]
Unfortunately, it still happens every now and then even without IntroTweaks. With the following error message:

![grafik](https://github.com/IAmBatby/LethalLevelLoader/assets/8191849/ee93eae6-34bf-4eb6-8f76-5bae7057f7c1)

**Comment by IAmBatby** [comment]
Should be resolved but this problem was due to how Intro-Skipping mods worked. Most if not all related mods have been tweaked to handle the feature more safely as far as I'm aware.
