### ISSUE TITLE
LethalExpansion moons are priced 0

### ISSUE THREAD

**Issue by AndreyMrovol** [IAmBatby/LethalLevelLoader#23]
As of latest update (v1.1.3) LethalExpansion moons' cost is 0:
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/32998721/13cb7363-aee7-40c3-8f19-4e6f60ffa02a)

This can be overriden using LLL's config to set moon price manually:
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/32998721/27bfd987-df42-4098-af5e-4a1545c35690)

**Comment by Xentax5** [comment]
I also have this issue. Please fix it, it's annoying. :D

Only "workaround" is to allow to modify the setting of the moon change price to the original value, but that just makes the moon all the same and overrides their default setting.

**Comment by Blarnix** [comment]
Also having this issue with other moon mods such as Orion.

**Comment by Xentax5** [comment]
> Also having this issue with other moon mods such as Orion.

Yes, same, could have formulate it better. It happens for all modded moons that are not managed by LethalLeverLoader.

**Comment by AndreyMrovol** [comment]
I've heard somebody mention it's caused by LECore, not by LE per se - I'll try to test this more extensively

**Comment by Mr-Twave** [comment]
> I've heard somebody mention it's caused by LECore, not by LE per se - I'll try to test this more extensively.

Let me know when you've got a resolution. I'll open a new issue in the LE core github. https://github.com/LethalMods/LethalExpansionCore

**Comment by AndreyMrovol** [comment]
After quick testing:

- Using only `LethalExpansion` its moons are not added *at all*
- Using only `LECore` (as well as both at the same time) all moons are added, but they all cost 0

**Comment by IAmBatby** [comment]
Unfortunately this is due to some improvements made in v1.1.0 that break LethalExpansion (and LethalExpansionCore) because of some older code that relies on an assumption that I change. This was directly reported to both developers a few days ago.

**Comment by AndreyMrovol** [comment]
> Unfortunately this is due to some improvements made in v1.1.0 that break LethalExpansion (and LethalExpansionCore) because of some older code that relies on an assumption that I change. This was directly reported to both developers a few days ago.

That's good to know, hoping that they resolve this issue 😇

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
