### ISSUE TITLE
Typing MOONS then Enter causes error and not opend moons

### ISSUE THREAD

**Issue by neverforu** [IAmBatby/LethalLevelLoader#27]
pls update

**Comment by Mr-Twave** [comment]
There's another issue created prior for the first part, but the second part I assume you mean that moons that weren't opened before will throw an error as well.

**Comment by DerTodlichEngel** [comment]
> There's another issue created prior for the first part, but the second part I assume you mean that moons that weren't opened before will throw an error as well.

same as issue #26

**Comment by Mr-Twave** [comment]
This is their first github issue. Give them a little credit for at least adding "not opend moons".

> > There's another issue created prior for the first part, but the second part I assume you mean that moons that weren't opened before will throw an error as well.
> 
> same as issue #26

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
