### ISSUE TITLE
ALL THE MODDED MOONS ARE FREE

### ISSUE THREAD

**Issue by KKaydoom** [IAmBatby/LethalLevelLoader#29]
I have confirmed that this mod is causing it and that it has made all modded moons using this and NOT using this free
this means legit any moon added became free even thes ones from magic wesley who does not use this mod for moons (like infernis, etern, or asteroid 13)

**Comment by LoafOrc** [comment]
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/33192068/c377fa43-b01d-41c1-9cc8-6850b57db1f5)

**Comment by KKaydoom** [comment]
okay im just gonna use 1.12 until it is fixed
