### ISSUE TITLE
Moons not loading / Stuck in "Waiting for crew..." screen

### ISSUE THREAD

**Issue by L1v1dDX** [IAmBatby/LethalLevelLoader#32]
I've been having this problem ever since installing LethalLevelLoader, but it could be that this problem is caused by something else. Seeking help here seems to be my best option. While I'm stuck in this screen a large amount of Unity Log Errors saying "Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time" are spammed into my console, although it seems to stop after roughly 10 seconds of continuous spamming, this still doesn't resolve my problem and keeps me stuck in the "Waiting for crew..." screen.
The Moon I am testing this on is "Triskelion" added by StarlancerMoons. I downloaded the Starlancer modpack with the Music, LethalLevelLoader, etc. After downloading I decided to update all the mods except for LethalLevelLoader, leaving it in Version 1.0.7 because I read in a Steam forum that it would fix the issue, which it didn't.
https://pastebin.com/j6ZrXvDB here's the entire Log.

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
