### ISSUE TITLE
Moon list would not open on latest update or Let me land on certain modded ones

### ISSUE THREAD

**Issue by Shirleylier** [IAmBatby/LethalLevelLoader#36]
On version 1.1.4 I tried to open the moon list, but nothing would happen. I could type the moons in by name, but I would have to do that for every one to see weather conditions and pricing. If I go down to version 1.1.2 it allows me to see the list, but it does not show all the modded moons on the list. I also could not access some moons as it says (CurrentMoontime) or something along that instead of weather. It won't let me confirm landing on those moons. I know the moon list is impacted by the LethalLevelLoader, but I do not know if it is also causing the selection issues.

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
