### ISSUE TITLE
New config overwrites modded moon+interior configs

### ISSUE THREAD

**Issue by Osborde** [IAmBatby/LethalLevelLoader#37]
The new config added with the recent update results in all modded moons having 0 route price, as well as removing certain mechanics with monster spawn weight with modded interiors (such as Shrimp with LC Office, which is _only_ supposed to spawn when the LC Office interior is rendered, but now has a chance to spawn on any planet due to the spawn chance added automatically in the config)

Please add option to completely ignore the LethalLevelLoader config for the sake of prioritizing other moon/interior configs

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
