### ISSUE TITLE
Config Incompatibility with Modded Scrap

### ISSUE THREAD

**Issue by ElvenWitchBirdy** [IAmBatby/LethalLevelLoader#41]
The config does not work properly when editing the scrap pool of any moon. It works well with vanilla loot, but not if it's from any mods.

I'll be using the modded moon Asteroid-13 as an example. Let's say I want have this as my customized setup...

Blue Folder:40,Red Folder:40,Stapler:40,Fire Extinguisher:34,Documents:26,Stun Baton:29,Banana:8,Coil:27,Bronze Trophy:13,Typewriter:19,Experiment Log Hyper Acid:8,Experiment Log Comedy Mask:8,Experiment Log Cursed Coin:8,Experiment Log BIO HXNV7:8,Old Computer:7,BIO-HXNV7:5,Mug:7,Remote:6,Old phone:4,Magnifying glass:4,Fancy lamp:3,Cash register:2,Fire hydrant:2,Retro PC:0,Computer Chip:0,Computer Fan:0,Gas Can:0,Metal Beam:0,CRT Monitor:0,Box Of Parts:0,Copper Wire Spool:0,Ball Bearing:0,Metal Disk:0,Small Motor:0,Stator:0,Air Compressor:0,Gear:0,Cog:0,Small Gear:0,Flathead Screw:0,Hex Screw:0,Panhead Screw:0,Floppy Disk:0,Big Wrench:0,Lost Employee Helmet:0,Lost Employee Tank:0,Aerial Dish:0,Old Missile:0,Diesel Generator:0,Oil Drum:0,Studio Camera:0,6 Pin Cable:0,Capacitor:0,Diode:0,Transistor:0,Magnet:0,Blue Tape:0,Tape Measure:0,Flip Phone:0,Control Panel:0,Car Battery:0,Piston:0,AC Unit:0,Alarm Clock:0,AA Battery:0,9V Battery:0,Polaroid Camera:0,Jet Engine:0,Lightbulb:0,Lighter:0,Neon Sign:0,Propane Tank:0,Traffic light:0,Vice:0,Arson Plush:1,Cookie Fumo:1,Toimari Plush:2,Hamis Plush:2,Dirty Arson Plush:1,Maxwell:1,Glizzy:1,Revolver:2,Gremlin Can:2,Toy Hammer:5,Gnarpy Plush:2,Army Helmet:1,Army Canteen:1,Gramophone:1,Old Radio:1,RockingHorse:1,TypeWriter:1,WheelRim:1,WireSpool:1,Bracken Plushie:1,Bunker Spider plushie:1,CoilHead Plush:8,Comedy mask Plushie:1,Lootbug Plushie:1,Scavenger Plushie:1,Tragedy Plushie:1

If Enable Content Configuration is set to true, then all it does is spawn in vanilla loot. It includes all the vanilla loot that's in the list above but somehow it was also including ones that aren't supposed to be in there like comedy/tragedy masks (probably because of the Plushie part).

Then I tried to set it to this...

Blue Folder:40,Red Folder:40,Stapler:40,Fire Extinguisher:34,Documents:26,Stun Baton:29,Banana:8,Coil:27,Bronze Trophy:13,Typewriter:19

But it just gets stuck in a forever-loading loop.

I wasn't able to test this part well enough but I think this also extends to spawn weights of modded entities such as Shy guy, Herobrine, or Boombas.

I can try to supply more information as requested but I'm not a modder.

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
