### ISSUE TITLE
[Question] add all custom dungeon interiors to all levels

### ISSUE THREAD

**Issue by MasterEvilAce** [IAmBatby/LethalLevelLoader#42]
Due to a lot of different configuration options, I'm wondering the best way to allow all interiors on all moons.
Most modded moons tend to use vanilla facility. If you use custom dungeon's own configuration, you basically won't get vanilla mansion.

I am looking at a baseline of all interiors being equal on all moons (vanilla and modded.)

Looking at LethalLevelLoader.cfg, I assumed setting:
Enable Content Configuration = true
Dungeon Injection Settings - Manual Mod Names List = Lethal Company:300, MoreMoonsMod: 100

to all of the dungeons would allow this to happen (additionally clearing the other Dungeon Injection Settings lines so specific moons won't have additional chance and what not.)

Unfortunately this doesn't seem to work? I just get facility constantly.

I am also wondering the difference between 
Vanilla Dungeon: 1. - Facility (Level1Flow)
Vanilla Dungeon: 3. - Facility (Level1FlowExtraLarge)
is extralarge only used for titan, and thus could be disabled? Otherwise you would get essentially facility having twice the chance.

**Comment by IAmBatby** [comment]
Targeting every piece of relevant content using Vanilla and Custom tags is the intended way yes. Some modifications of Vanilla based weights may not work.
