### ISSUE TITLE
Custom moons weather is not synced

### ISSUE THREAD

**Issue by Entity378** [IAmBatby/LethalLevelLoader#43]
For some reason, when you try to load a custom moon with LethalLevelLoader the weather of each individual moon becomes desyced between the clients and the server. **(It's not just a graphical bug!!!)**

The server sees this:
![Server](https://github.com/IAmBatby/LethalLevelLoader/assets/150670165/037d4d4e-e8c0-42f6-af4c-600546332d19)

Instead the Clients see this:
![clients](https://github.com/IAmBatby/LethalLevelLoader/assets/150670165/dc667e58-52c5-4bda-bf02-59b185e25e43)

**Comment by StonedGoat** [comment]
Bump, had the same issue, seems to also cause the ship to be unable to land. I'm sticking to 1.0.7, at least that version works consistently.. :T

**Comment by Entity378** [comment]
> Bump, had the same issue, seems to also cause the ship to be unable to land. I'm sticking to 1.0.7, at least that version works consistently.. :T

During my testing I was unable to replicate the ship's inability to land
​
​

**Comment by ItsTripull** [comment]
I have the same issue with weather using LLL. As of right now, to solve the Weather Desync Issue, the mod "WeatherTweaks" seems to fix this issue after countless attempts at finding the answer to this issue. Until the dev updates the mod to hopefully improve the sync errors, i'd suggest using this to sync the weather.
