### ISSUE TITLE
Wouldnt go past the doors screen

### ISSUE THREAD

**Issue by JbcolePAGA** [IAmBatby/LethalLevelLoader#44]
Had me going crazy for hours tryna find the issue of if everyone dies and it does the cinematic camera follow then cut showing the open door then closing, it wouldnt go past from there it will be stuck your able to press escape and put quit but thats it. Now it doesnt do that no more but i rather still make this as a headsup of this happening.

**Comment by IAmBatby** [comment]
Should be resolved in future versions.
