### ISSUE TITLE
Latest version (1.1.6) breaks menu screen after splash screen

### ISSUE THREAD

**Issue by Phyore** [IAmBatby/LethalLevelLoader#46]
Updated from 1.1.4 to 1.1.6 and the game menu just sits on a black screen with the accessories button in the bottom right. No music.

Downgraded for now as it was the only mod causing issues. 

Using this modpack: https://thunderstore.io/c/lethal-company/p/Hidlden/LethalFuzz/ (To get a list of other mods)

**Comment by mkikets99** [comment]
@IAmBatby 
Having the same issue here...
Providing last log strings that gives explanation:

```
[Warning:LethalLevelLoader] SceneManager has attempted to load MainMenu Scene before AssetBundles have finished loading. Pausing request until LethalLeveLoader is ready to proceed.
[Error  : Unity Log] Panel label not found.
[Error  : Unity Log] Delete file game object not found.
[Error  : Unity Log] Error occurred while refreshing save buttons: Object reference not set to an instance of an object
[Error  : Unity Log] Error occurred while updating files panel rect: Failed to find FilesPanel RectTransform.
[Error  : Unity Log] An error occurred during initialization: Object reference not set to an instance of an object
[Info   :ainavt.lc.lethalconfig] Injecting mod config menu into main menu...
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
IngamePlayerSettings+<waitToLoadSettings>d__17.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0065)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)
```

**Comment by xlifi** [comment]
Got the same thing when making my own modpack, issue disappeared after disabling Orion v2.1.0 and 71Gordion v1.0.1

**Comment by mkikets99** [comment]
> Looks like an issue with many/big packages. Same issue disappeared on my own modpack after disabling Orion v2.1.0 and 71Gordion v1.0.1
> Edit: Happened on 1.1.4 as well, works on 1.1.0
> Edit 2: I'm using [SkipToMultiplayerMenu](https://thunderstore.io/c/lethal-company/p/FlipMods/SkipToMultiplayerMenu/) mod

As far as i saw, the only problem is SkipToMultiplayerMenu mod... 1.1.6 working ok with STMM off...

**Comment by IAmBatby** [comment]
Should be resolved but this problem was due to how Intro-Skipping mods worked. Most if not all related mods have been tweaked to handle the feature more safely as far as I'm aware.
