### ISSUE TITLE
[BUG] Weather de-sync issues, and a temporary solution for user

### ISSUE THREAD

**Issue by CoolLKKPS** [IAmBatby/LethalLevelLoader#49]
so here's the moons and dungeons i have:
SCPFoundationDungeon
Scoopys Variety Mod
E Gypt Moon
SecretLabs
LC Office
Outpost 31
MoreInteriors

And the LevelLoader version: 1.1.6

if u need logs, pls tell me what log levels u need, so many mod wiki that i don't want to read....

**Comment by CoolLKKPS** [comment]
effect every moons, no matter vanilla or modded moons, all have this issues, i notice u already have another issue report, so i will mention that: https://github.com/IAmBatby/LethalLevelLoader/issues/43
and yea i also have this issue: https://github.com/IAmBatby/LethalLevelLoader/issues/45

**Comment by CoolLKKPS** [comment]
@IAmBatby not sure why can cause that, but i think community need a standard right now, base on that standard code and tools to fix many conflict issues, one and for all, right now u just always receive many issues

**Comment by ajsglist** [comment]
can confirm that LLL 1.1.6 appears to be giving weather desyncs of some kind.  Last night players saw quicksand pits in different locations despite using the same mods/configs and generating the same seed

observed on vanilla maps

**Comment by ajsglist** [comment]
I don't think the ticket you linked has anything to do with weather desyncs. What am I missing?
