### ISSUE TITLE
Too many fire exits

### ISSUE THREAD

**Issue by Entity378** [IAmBatby/LethalLevelLoader#5]
In moons loaded by LethalExpansionCore, any type of dungeon is generated with too many fire exits, causing an out of bounds when exiting one of them. I tried to see if it also happened in the vanilla moons, the dungeons in that case are generated with the correct number of fire exits.

**Comment by IAmBatby** [comment]
Resolved in the 1.0.7 Update which moved from prefab injection to direct scene loading.
