### ISSUE TITLE
Can't go to modded maps

### ISSUE THREAD

**Issue by Yukine19** [IAmBatby/LethalLevelLoader#50]
Not able to go into modded maps. On the terminal I am able to route the map, however I cannot confirm the map. Please see picture and log output for details.

LE owner says that the newer updates of LLL is most likely the reason. 

![Desktop Screenshot 2024 02 15 - 19 34 30 62](https://github.com/IAmBatby/LethalLevelLoader/assets/155184668/cb65d425-1586-4287-b14f-e4e06f2f207a)

[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/14319897/LogOutput.log)

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
