### ISSUE TITLE
[BUG] Game softlocks while loading random seed

### ISSUE THREAD

**Issue by Enderneer** [IAmBatby/LethalLevelLoader#52]
Been having an issue lately with moons not fully loading in, resulting in a softlock, and the logs from the command prompt point towards LethalLevelLoader having something to do with it.

Essentially, whenever I go to a moon, there is a random chance that the game will softlock on the "Random seed: XXXXXXXX" prompt. Seems to be more common on modded moons. For example, I tried to load into the modded moon Aquatis multiple times, and got the bug somewhat consistently. 

![20240220151930_1](https://github.com/IAmBatby/LethalLevelLoader/assets/53953046/9c3a6bac-82eb-4dcf-96b9-ad56f333d0cf)

![2024-02-20 15_19_57-Lethal Company](https://github.com/IAmBatby/LethalLevelLoader/assets/53953046/d2cab90c-dacf-4f08-8dff-1767cf7a86a5)

Here's the log for when the error occurs if you're curious.

[Error Log.txt](https://github.com/IAmBatby/LethalLevelLoader/files/14351321/Error.Log.txt)

**Comment by davidgamero** [comment]
I've had the same issue on Aquatis, but Aquatis is built using HolographicWings' LethalExpansion, which can conflict with LethalLevelLoader.
Recent it's been extremely delicate to run both LLL and LE together so I've had better luck just keeping seperate mod profiles with one for all the LE moons and one for LLL moons tbh

**Comment by slayer6409** [comment]
If you downgrade LLL to version 1.0.7 it works just fine

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
