### ISSUE TITLE
Numbering for Moons and Interiors in Config Resets My Changes

### ISSUE THREAD

**Issue by Matt-662607015** [IAmBatby/LethalLevelLoader#53]
Whenever the load order changes for moons or interiors, the moons or interiors are re-numbered in the config, causing there to be duplicate sections with different numbers. The problem with this is that the new sections are at default settings, so I have to redo the LLL config every time I add a new moon or interior.

A hypothetical example: I add Bozoros moon, which is placed in the config as moon number 5; however, Egypt was already number 5 and now becomes number 6, so LLL adds a new Egypt section as number 6. Now there are two sections for Egypt, but only number 6 is used and all the Egypt settings are back to default.

This is a problem in my modpack because this re-numbering is chained between several moons or interiors, causing large sections of the config to reset every time I add a new moon or interior. For example, if I am unlucky enough to add a new moon that is loaded first, it would be number 1, causing a chain reaction where all the other moons are re-numbered and their config sections reset.

**Comment by Matt-662607015** [comment]
example of my pain
![image](https://github.com/IAmBatby/LethalLevelLoader/assets/41337151/f25a9cda-f72c-4032-9586-169779434412)

**Comment by awesfdawe** [comment]
same issue

**Comment by Matt-662607015** [comment]
I'm going to use this fork until the issue is fixed:
https://thunderstore.io/c/lethal-company/p/Refract/LethalLevelLoaderFixed/
