### ISSUE TITLE
"switch" command in terminal goes to moons catalogue

### ISSUE THREAD

**Issue by TtimmEwath** [IAmBatby/LethalLevelLoader#54]
When viewing the monitor on the terminal, the "switch" command should change the currently monitored player to the next player in the cycle. Currently the "switch" command doesn't do that and instead brings up the exomoons catalogue. This makes it harder/slower to change the monitor. Interestingly typing "switch [player_name]" still works and changes the monitor to view that player.

**Comment by remiX-** [comment]
+1 here.

It is not just limited to `switch` but also affects commands from other mods that are non-confirmation and also have a `terminalEvent` set

**Comment by legionofnod** [comment]
It's not just the latest version of the mod that has this problem. The problem seems to have been around since version 1.1.0. And it can happen in games where only this mod is installed

**Comment by Fl4sHNoX** [comment]
+1

The `stock` command added by the [StockOverview](https://github.com/Squall4120/StockOverview) mod also redirects to the Moons screen of the terminal instead of showing the intended stock screen:

https://github.com/IAmBatby/LethalLevelLoader/assets/3759901/4ca6d965-ac90-419d-ab31-0039379ecbb4

**Comment by IAmBatby** [comment]
Will be fixed in the forthcoming update. Apologies on the delay as I've been unwell. Thank you all for the report and apologies for the inconvenience.

**Comment by VioletXe** [comment]
Will the update fix ALL of them? I recently found that the "Slots" commands from the gamba mod also does the same thing.

**Comment by Fl4sHNoX** [comment]
It seems like the "Simulate" command doesn't work either.

**Comment by Mr-Twave** [comment]
> Will be fixed in the forthcoming update. Apologies on the delay as I've been unwell. Thank you all for the report and apologies for the inconvenience.

Get well soon. 

Let it be known you are a special hard working altruistic dev. 🥺

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
