### ISSUE TITLE
Modded Moons dont spawn modded scrap

### ISSUE THREAD

**Issue by Catpyre** [IAmBatby/LethalLevelLoader#56]
It looks like LethalLevelLoader only spawns vanilla loot on custom moons in the config and manually inputting modded scrap into the spawn list doesn't change that? This wasnt an issue when using a mod liek AdvancedCompany, though for variosu reasons I have moved away from that mod, so im curious if this behaviour is currently intended or if its a bug?

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
