### ISSUE TITLE
moon modification disables scarlet mansion spawns and cost wont change for factory x

### ISSUE THREAD

**Issue by TheDynamic7** [IAmBatby/LethalLevelLoader#58]
after setting all options to true for every moon and changing the cost to lets say 900 each, only a random select few at first changed to 900 and then after multiple relaunches the rest o the vanilla followed. but the rest of the modded moons stay default. i use wesleys moons, factory x and mental hospital.

Edit. factory x is the main conflict here and doesnt seem supported by LLL i may have broken the terminal and prices trying to modify it. its strange it allows any modification to begin with.

on another note though, modifying any moon disables scarlet mansion from spawning, while other interiors dont suffer the same fate, is there a reason/cause for that?

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
