### ISSUE TITLE
Switch broken for ship mom

### ISSUE THREAD

**Issue by RPratt009** [IAmBatby/LethalLevelLoader#59]
Running into an issue when trying to use the "switch" command with "view monitor" on the ships computer. it seems to pull open the list of moons instead of swapping between who you are viewing

I have verified that it works while this mod is disabled and only stops working once enabled

018e34b4-9430-f310-af10-b25602fa1dbf

**Comment by remiX-** [comment]
The mod owner is aware of this, but hasn't updated the mod for some time - not sure what's happening

https://github.com/IAmBatby/LethalLevelLoader/issues/54

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
