### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by pil0lo** [IAmBatby/LethalLevelLoader#61]
I don't know which one it is because of.
It keeps saying the version doesn't match.
Adding a new map does not add it.

![1](https://github.com/IAmBatby/LethalLevelLoader/assets/143984023/f546c967-a70b-4933-8aac-87f08c0ac81d)
![2](https://github.com/IAmBatby/LethalLevelLoader/assets/143984023/9116c2e0-4d5c-4e71-8303-c98df7493c4c)

This is the mod code I am using.
Would it be easier to find out if I had this??

018e84d8-80c2-e8af-e1d6-71059ff6d44f

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
