### ISSUE TITLE
[Issue/Conflict] Conflict with ConfigurableCompany and/or LethalCompanyVariables by AMRV, and issues

### ISSUE THREAD

**Issue by CoolLKKPS** [IAmBatby/LethalLevelLoader#70]
btw [Fatal  : OldLLLLib] No OldLLL version found! ???

**Comment by CoolLKKPS** [comment]
link issue ticket: https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/issues/19

**Comment by CoolLKKPS** [comment]
and issue: 
1. load a vanilla save will cause blackscreen, only way to play is create a new save

**Comment by xVoidie** [comment]
> btw [Fatal : OldLLLLib] No OldLLL version found! ???

this error is caused by MrovLib which is used by TerminalFormatter and WeatherTweaks

**Comment by CoolLKKPS** [comment]
fixed
