### ISSUE TITLE
v50 Spawning in the void

### ISSUE THREAD

**Issue by Phyore** [IAmBatby/LethalLevelLoader#71]
Running latest update of all mods.

Disabling LLL allows the player to load in fine. Having it enabled causes spawning in the "void" (green foggy screen with 'grab (E)')

Running LLL on its own in a fresh profile and player loads fine. I can only assume it it conflicting with a mod but cannot work out which.

[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/15096709/LogOutput.log)

**Comment by Phyore** [comment]
> I also had this issue, it seems to only happen with existing saves before the update, however making a new save allows me to load into the game just fine

Just tried deleting a save and then making a new one and still get the issue.

**Comment by ValentinLnn** [comment]
Did you have a modpack for moons, like Tolian ? Modpacks made it buggy for me, so i manually downloaded each moons.

**Comment by Uxsee** [comment]
I have an issue similar to this, but instead of me loading into the void it's my friends that load into the void when they join in.

**Comment by EfJun1** [comment]
> I have an issue similar to this, but instead of me loading into the void it's my friends that load into the void when they join in.

My friend are still having the same issue with the latest version.

**Comment by tgadberry1** [comment]
I could also work around this by creating a new save file. You might also check to see if you have one or more versions of LethalExpansion (LE) installed, as certain moon packs include it as a dependency. The latest LE-Preview and separate LE-Core fork could cause conflicts with the now deprecated original LE.

**Comment by EfJun1** [comment]
> I could also work around this by creating a new save file. You might also check to see if you have one or more versions of LethalExpansion (LE) installed, as certain moon packs include it as a dependency. The latest LE-Preview and separate LE-Core fork could cause conflicts with the now deprecated original LE.

I have tried turning off the LethalExpansionCore + ImmseriveScraps, my friend and I have the same settings and he couldn't join, we will have to play with the levelloader disable for now.

**Comment by IAmBatby** [comment]
Resolved as Lethal Expansion is now deprecated. Was also likely due to using older, now invalid save files. Apologies for the inconvience.
