### ISSUE TITLE
Lethal Level Loader overwriting terminalPlus formatting 

### ISSUE THREAD

**Issue by zhongjiedong** [IAmBatby/LethalLevelLoader#74]
No idea who's at fault here, posting on both repos.

**Comment by CoolLKKPS** [comment]
1.2.2 fix this issue, but cause other issue now
and, its TerminalFormatter not TerminalPlus

For CN mainland user:
你应该在两个库中建立问题之后，再附上另一个库的问题链接来做到提及问题的作用

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
