### ISSUE TITLE
The terminal's company instructions have no effect

### ISSUE THREAD

**Issue by lenmon666** [IAmBatby/LethalLevelLoader#77]
When using the company command on the terminal, it has no effect. And it will also confuse the display content of planets in the Moons list!
Using LethalLevelLoader 1.2.2! @IAmBatby  May I ask what the situation is?

**Comment by rootbeer2222** [comment]
Having the same issue here

**Comment by ZD-ChaofanJ** [comment]
Can confirm that trying to navigate to the Company Building does not work using LethalLevelLoader v1.2.2.

**Comment by rootbeer2222** [comment]
I FOUND A TEMPORARY FIX

install the mod "AutoCompanyBuilding" by La_chips and it will just force you to the company building and work.

**Comment by rootbeer2222** [comment]
> Can confirm that trying to navigate to the Company Building does not work using LethalLevelLoader v1.2.2.

I FOUND A TEMPORARY FIX

install "AutoCompanyBuilding" by La_chips and at day 0 it will force you to the company building and it works.

**Comment by fanuch** [comment]
The actual temporary fix is to downgrade LethalLevelLoader 1.2.1 until the issue can be patched.

P.S. Commenting "me too" contributes nothing to the conversation. Just thumbs up to reduce the noise on an issue.

**Comment by CoolLKKPS** [comment]
same issue

**Comment by ZD-ChaofanJ** [comment]
> The actual temporary fix is to downgrade LethalLevelLoader 1.2.1 until the issue can be patched.
> 
> P.S. Commenting "me too" contributes nothing to the conversation. Just thumbs up to reduce the noise on an issue.

Don't downgrade to 1.2.1. This version has a tendency to corrupt saves/items.

**Comment by CoolLKKPS** [comment]
i got a temporary solution now, check #78

**Comment by CoolLKKPS** [comment]
in short, u cannot rely on LLL Terminal Formatting in 1.2.2, ok that really break my trust a little

**Comment by fanuch** [comment]
> Don't downgrade to 1.2.1. This version has a tendency to corrupt saves/items.

Certainly made for an interesting series of games. Loaded in with three jetpacks instead of pro flashlights :laughing: 

@CoolLKKPS  are you saying to pair the LethalLevelLoader 1.2.2 with TerminalFormatter 0.2.3?

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
