### ISSUE TITLE
[Dependency for compatibility] LoadStone And Terminal API, and temporary solution for 1.2.2, to fix "com" command

### ISSUE THREAD

**Issue by CoolLKKPS** [IAmBatby/LethalLevelLoader#78]
i am more trust LoadStone and Terminal API now, loading time still not enough fast, and still have some terminal issues that really annoying

**Comment by CoolLKKPS** [comment]
let #77 to handle

**Comment by CoolLKKPS** [comment]
download "TerminalFormatter" mod to fix "com" command, for 1.2.2 and #74

**Comment by CoolLKKPS** [comment]
make sure u "Enable node Moons", to display custom level add by LLL
and if u have WeatherTweak, u might also need to "Enable node Route"

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
