### ISSUE TITLE
Company Building Inaccessible

### ISSUE THREAD

**Issue by VioletXe** [IAmBatby/LethalLevelLoader#80]
018f2624-51ea-a0c6-700b-3e415748f872

Was making a modpack for stupid fun on stream, but we found that the company was inaccessible. Disabling (LLL) allowed us to access the moon again, but I don't know why.

**Comment by Trixmor** [comment]
Same

**Comment by IIWolfieII** [comment]
Also happened to me.

From what I remember, I used LLL, it's dependencies, all of Tolian's moons and bunch of other things.

We did 3 days' worth of travelling and when it was time to go to the company, we typed it into the terminal.

However, the terminal would not let you press enter with any combination for the company building.

There seemed to be an error with some sort of Terminal Manager script and an array index out of bounds.

Another problem seems to also be that some of the moons just randomly don't appear in the terminal moons list.

Modpack: 018f2685-46bd-a231-6896-14f15390913b

**Comment by Trixmor** [comment]
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
LethalLevelLoader.TerminalManager.LockedNodeEventTest (TerminalNode& currentNode, TerminalNode& loadNode) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_0006)
LethalLevelLoader.TerminalManager.OnBeforeLoadNewNode (TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_004D)
LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_001B)
(wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
Terminal.OnSubmit () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_00FB)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by cfazilleau** [comment]
Same here, doesn't happen when playing on 1.2.1, only with LLL1.2.2
maybe related to the ExtendedLevel.IsRouteLocked

**Comment by scrongled** [comment]
Same issue for me. Trying to hit after enter with any line that'd trigger the confirm or deny prompt, just results in not doing anything.

**Comment by tocram1** [comment]
> You can use AutoCompanyBuilding to resolve this

I tried using that, and in most cases it helps, but if one player opens up the terminal and flies to another planet by mistake... you are never going back to company building ever again on this save 💀 even after reloading if the game has auto-saved

**Comment by 1410677474** [comment]
use TerminalFormatter



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 30, 2024 23:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IAmBatby/LethalLevelLoader] Company Building Inaccessible (Issue#80)




  
You can use AutoCompanyBuilding to resolve this
  
I tried using that, and in most cases it helps, but if one player opens up the terminal and flies to another planet by mistake... you are never going back to company building ever again on this save 💀 even after reloading if the game has auto-saved

**Comment by tocram1** [comment]
Yeah I just found out about this, I'll test this solution in a few hours when I'm on my computer. Thanks for the tip, I'm sure this will help at least someone else here until a patch is released ;)

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
