### ISSUE TITLE
When people join they are in a black void

### ISSUE THREAD

**Issue by jovn1234567890** [IAmBatby/LethalLevelLoader#84]
I added the mod to fix the ability to go to the company building but now when my friends try to join they are in a black void even when we land instead of in the ship.

**Comment by 1410677474** [comment]
The problem is caused by BetterSprayPaint

**Comment by jovn1234567890** [comment]
> The problem is caused by BetterSprayPaint

I don't even have that one, I fixed the issue by downgrading LLL to 1.2.1 that fixed everything.

**Comment by TheCraftedGamer** [comment]
for me it was minecraft interiors and pool rooms. i still have betterspraypaint.
