### ISSUE TITLE
[bug] Item ID's on existing saves become scrambled after enabling LLL

### ISSUE THREAD

**Issue by DravenXD** [IAmBatby/LethalLevelLoader#89]
For instance, after enabling LLL and it's dependencies; gold bars become hair dryers, paintings become plastic fish and knives become eggs. If the game is not saved and reloaded, the items will return to their intended state.
I do have at least one mod that adds a custom item to the game, that being the rolling giant mod, however, disabling this mod does not effect the scrambled ID's, and most items still transform into the same items as described before, that being gold to hair dryers, etc.

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
