### ISSUE TITLE
 cant' type company command

### ISSUE THREAD

**Issue by chabu2** [IAmBatby/LethalLevelLoader#91]
how to fix a command i cant type company when use this mod

**Comment by Royalforce1** [comment]
Same here. Not Custom moons either, I have all custom moons disabled, tried changing LLL config, nothing fixes it. It was working yesterday, but despite no update, things seem to be broken now.

**Comment by Kraywell** [comment]
Hi guys! I have temporary solution, use [https://thunderstore.io/c/lethal-company/p/mrov/TerminalFormatter/](url) mod to fix this.

**Comment by Royalforce1** [comment]
There's that, and there's also a mod I found that's explicitly called LLLCantRouteToCompanyFix that works as well.

**Comment by DravenXD** [comment]
Yeah, this was a major issue for me as well. Glad there's a temporary fix. Hopefully this gets patched soon.

**Comment by Royalforce1** [comment]
Update: the mod I mentioned just installs the terminal formatted mod, and also I've been playing Welsey's Moons and idk if it's a him problem or a LLL problem (prolly Welsey's problem), but custom loot has trouble spawning all of a sudden.

**Comment by Kraywell** [comment]
Maybe both. 
But i play with custom interiors with custom loot and don't have any problems with spawn custom items. Welsey recently release custom interior. Maybe problem in this mod?

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
