### ISSUE TITLE
Performance issues when entering and leaving ship

### ISSUE THREAD

**Issue by mrKallah** [IAmBatby/LethalLevelLoader#97]
We were playing with amongst other mods MoreCompany and this might be compatibility issue, I am not sure, however on the 11th we were testing the mods and ensuring they worked as intended with two players and it worked fine, then when we were playing on the 12th with 7 people we had issues where every time someone entered and left the ship, the game would lag out for the player and the host, no matter where the host was. It only happens on modded moons, not on vanilla ones, even with everything installed, hence writing here. The game was pretty much unplayable for the host as he would experience sub 5 fps every time someone did something, and everyone else would also notice major lag spikes randomly when people entered or left the ship.

**Comment by mrKallah** [comment]
Oh and we were using the TerminalFormatter mod to enable us to fly to the company moon, but we used that both the 11th and 12th

**Comment by Kablumbaa** [comment]
@mrKallah Happens to me on wesleys moons i don't think it has anything to do with this mod

**Comment by IAmBatby** [comment]
LethalLevelLoader shouldn't be doing anything in regards to this to cause any performance issues, I can't actually think of anything it does related to this. I'd suggest reaching out to the authors of the custom moons utilizing LethalLevelLoader instead.
